version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: price_tracker_db
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U myuser -d mydatabase" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - local


  bot:
    build: .
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      DATABASE_URL: ${DATABASE_URL}
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8443:8443"
    restart: unless-stopped
    networks:
      - local

networks:
  local:

volumes:
  postgres_data: