version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: price_tracker_db
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - local


  bot:
    command: bash -c "alembic upgrade head && python app.py"
    build: .
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      DATABASE_URL: ${DATABASE_URL}
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8443:8443"
    restart: unless-stopped
    volumes:
      - .:/app
    networks:
      - local

networks:
  local:
